[package]
name = "lab_02"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick_sort = { path = "..\\quick_sort" }
file_parser = { path = "..\\file_parser" }